import type { ProviderName, ProviderUsageCapability } from './types.js'

export const DEFAULT_USAGE_CAPABILITIES: ProviderUsageCapability[] = [
  capability({
    provider: 'openai',
    displayName: 'OpenAI',
    status: 'available',
    usageApi: 'GET /v1/organization/usage/{service}',
    billingApi: 'GET /v1/organization/costs',
    masterCredential: 'OPENAI_ADMIN_KEY from an organization owner',
    attribution: 'project_id, api_key_id, user_id, model',
    cadence: 'Usage buckets down to 1 minute; costs daily',
    sourceUrl: 'https://platform.openai.com/docs/api-reference/usage',
    notes: 'Use the costs endpoint for invoice reconciliation; usage can differ slightly from billed costs.',
  }),
  capability({
    provider: 'anthropic',
    displayName: 'Anthropic',
    status: 'available',
    usageApi: 'GET /v1/organizations/usage_report/messages',
    billingApi: 'GET /v1/organizations/cost_report',
    masterCredential: 'ANTHROPIC_ADMIN_KEY from an organization admin',
    attribution: 'api_key_id, workspace_id, model, service_tier',
    cadence: 'Usage buckets down to 1 minute; cost report daily',
    sourceUrl: 'https://docs.anthropic.com/en/api/data-usage-cost-api',
    notes: 'Admin API is unavailable for individual accounts.',
  }),
  capability({
    provider: 'openrouter',
    displayName: 'OpenRouter',
    status: 'limited',
    usageApi: 'GET /api/v1/generation?id={generation_id}',
    billingApi: 'GET /api/v1/key for limits and credits',
    masterCredential: 'OPENROUTER_API_KEY per account/key',
    attribution: 'generation id, model, app_id, external_user',
    cadence: 'Per completed generation; no documented org-wide historical usage export',
    sourceUrl: 'https://openrouter.ai/docs/api-reference/get-a-generation',
    notes: 'For accurate product cost, store generation ids or enable usage accounting at request time.',
  }),
  capability({
    provider: 'stripe',
    displayName: 'Stripe',
    status: 'available',
    usageApi: 'GET /v1/balance_transactions',
    billingApi: 'GET /v1/balance_transactions',
    masterCredential: 'STRIPE_SECRET_KEY or restricted key with read access',
    attribution: 'metadata, customer, transaction id, reporting_category',
    cadence: 'Ledger rows in near real time',
    sourceUrl: 'https://docs.stripe.com/api/balance_transactions',
    notes: 'Balance transactions are the recommended accounting ledger for gross revenue, fees, refunds, and payouts.',
  }),
  capability({
    provider: 'github',
    displayName: 'GitHub',
    status: 'available',
    usageApi: 'GET /organizations/{org}/settings/billing/usage',
    billingApi: 'GET /organizations/{org}/settings/billing/usage',
    masterCredential: 'GitHub token with organization Administration read permission',
    attribution: 'repositoryName, product, sku, cost center',
    cadence: 'Daily/monthly summarized reports',
    sourceUrl: 'https://docs.github.com/en/rest/billing/usage',
    notes: 'Requires enhanced billing platform access and org admin, enterprise owner, or billing manager permissions.',
  }),
  capability({
    provider: 'cloudflare',
    displayName: 'Cloudflare',
    status: 'limited',
    usageApi: 'POST /client/v4/graphql',
    billingApi: 'Billing subscriptions/profile APIs and dashboard billable usage',
    masterCredential: 'CLOUDFLARE_API_TOKEN with Account Analytics Read and Billing Read',
    attribution: 'account, zone, dataset-specific dimensions',
    cadence: 'Analytics can be near real time; invoice reconciliation is product-specific',
    sourceUrl: 'https://developers.cloudflare.com/analytics/graphql-api/',
    notes: 'Cloudflare warns GraphQL analytics should not be treated as exact billing usage for every product.',
  }),
  capability({
    provider: 'vercel',
    displayName: 'Vercel',
    status: 'available',
    usageApi: 'GET /billing/charges or vercel usage --format json',
    billingApi: 'GET /billing/charges',
    masterCredential: 'VERCEL_TOKEN with access to the team context',
    attribution: 'team, project, service, SKU/FOCUS dimensions',
    cadence: '1-day granularity; up to 1-year ranges',
    sourceUrl: 'https://vercel.com/changelog/access-billing-usage-cost-data-api',
    notes: 'The CLI also exposes usage and cost JSON for the active team.',
  }),
  capability({
    provider: 'aws',
    displayName: 'AWS',
    status: 'available',
    usageApi: 'Cost Explorer GetCostAndUsage',
    billingApi: 'Cost Explorer GetCostAndUsage / Cost and Usage Report',
    masterCredential: 'IAM role or access key with ce:GetCostAndUsage',
    attribution: 'linked account, service, usage type, tags, cost categories',
    cadence: 'Daily/monthly; hourly for selected recent data',
    sourceUrl: 'https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetCostAndUsage.html',
    notes: 'AWS Organizations management accounts can access member account cost and usage.',
  }),
  capability({
    provider: 'google',
    displayName: 'Google Cloud / Gemini',
    status: 'requires-export',
    usageApi: 'Cloud Billing export to BigQuery',
    billingApi: 'Cloud Billing BigQuery export and Pricing API',
    masterCredential: 'Billing account IAM plus BigQuery read access',
    attribution: 'billing account, project, service, SKU, labels',
    cadence: 'Exported throughout the day; no simple API-key-level cost endpoint',
    sourceUrl: 'https://cloud.google.com/billing/docs/how-to/export-data-bigquery',
    notes: 'Use detailed billing export for cost and resource-level usage; Pricing API provides SKU prices.',
  }),
  capability({
    provider: 'twilio',
    displayName: 'Twilio',
    status: 'available',
    usageApi: 'GET /2010-04-01/Accounts/{AccountSid}/Usage/Records.json',
    billingApi: 'Usage Records price fields',
    masterCredential: 'Main Account SID/Auth Token or API key; subaccounts supported',
    attribution: 'account SID, subaccount, category',
    cadence: 'Daily/monthly/all-time subresources',
    sourceUrl: 'https://www.twilio.com/docs/usage/api/usage-record',
    notes: 'includeSubaccounts can include master account and subaccount usage.',
  }),
  capability({
    provider: 'sendgrid',
    displayName: 'SendGrid',
    status: 'limited',
    usageApi: 'GET /v3/stats',
    billingApi: 'No documented invoice-cost API; estimate from stats and plan/rate card',
    masterCredential: 'SENDGRID_API_KEY with stats read permissions',
    attribution: 'parent/subuser via on-behalf-of, category/date stats',
    cadence: 'Daily, weekly, or monthly stats',
    sourceUrl: 'https://www.twilio.com/docs/sendgrid/api-reference/stats/retrieve-global-email-statistics',
    notes: 'Stats expose email activity, not exact invoice rows.',
  }),
  capability({
    provider: 'resend',
    displayName: 'Resend',
    status: 'limited',
    usageApi: 'Emails API, webhooks, and dashboard activity',
    billingApi: 'No public billing usage API found in official docs',
    masterCredential: 'RESEND_API_KEY with full access for account resources',
    attribution: 'domain, email id, webhook event',
    cadence: 'Event driven; usage counts must be derived',
    sourceUrl: 'https://resend.com/docs/dashboard/api-keys/introduction',
    notes: 'Use webhooks or the email activity API for internal metering until a billing API exists.',
  }),
  capability({
    provider: 'supabase',
    displayName: 'Supabase',
    status: 'limited',
    usageApi: 'Project Metrics API plus dashboard usage',
    billingApi: 'No documented organization invoice API; dashboard shows usage and upcoming invoice',
    masterCredential: 'Supabase PAT or project metrics credentials',
    attribution: 'organization, project, metric series',
    cadence: 'Metrics API is scrape-based; billing dashboard is org-level',
    sourceUrl: 'https://supabase.com/docs/guides/platform/metrics/',
    notes: 'Supabase billing is organization-based; project metrics do not fully replace invoice data.',
  }),
  capability({
    provider: 'sentry',
    displayName: 'Sentry',
    status: 'limited',
    usageApi: 'Events count and project event APIs',
    billingApi: 'No documented Stats page usage API',
    masterCredential: 'SENTRY_AUTH_TOKEN from an internal integration',
    attribution: 'organization, project',
    cadence: 'Endpoint-dependent',
    sourceUrl: 'https://sentry.zendesk.com/hc/en-us/articles/37505113730715-Does-Sentry-expose-an-API-for-usage-stats',
    notes: 'Official support says the Stats page has no documented API; events endpoints can approximate usage.',
  }),
  capability({
    provider: 'slack',
    displayName: 'Slack',
    status: 'limited',
    usageApi: 'Enterprise Grid Audit Logs API',
    billingApi: 'No general billing usage API for app/API costs',
    masterCredential: 'Enterprise owner user token with auditlogs:read',
    attribution: 'enterprise org, workspace, actor, action',
    cadence: 'Audit-event stream/query',
    sourceUrl: 'https://docs.slack.dev/admins/audit-logs-api',
    notes: 'Useful for governance and activity, not direct cost accounting.',
  }),
  capability({
    provider: 'discord',
    displayName: 'Discord',
    status: 'not-available',
    usageApi: 'Rate-limit headers only',
    billingApi: 'No provider billing/usage cost API for bot API usage',
    masterCredential: 'DISCORD_BOT_TOKEN per bot',
    attribution: 'bot/application and route buckets',
    cadence: 'Request-time rate-limit telemetry',
    sourceUrl: 'https://docs.discord.com/developers/topics/rate-limits',
    notes: 'Discord bot API usage is controlled by rate limits rather than usage-based provider billing.',
  }),
]

export function usageCapabilitiesForProviders(providers: Iterable<ProviderName>): ProviderUsageCapability[] {
  const known = new Map(DEFAULT_USAGE_CAPABILITIES.map((item) => [item.provider, item]))
  return [...new Set(providers)]
    .sort((a, b) => a.localeCompare(b))
    .map((provider) => known.get(provider) ?? capability({
      provider,
      displayName: displayProviderName(provider),
      status: provider === 'unknown' ? 'unknown' : 'limited',
      usageApi: 'Provider-specific adapter required',
      billingApi: 'Provider-specific adapter required',
      masterCredential: 'Not configured',
      attribution: 'Unknown',
      cadence: 'Unknown',
      sourceUrl: '',
      notes: 'No official usage/billing adapter has been mapped yet.',
    }))
}

function capability(value: ProviderUsageCapability): ProviderUsageCapability {
  return value
}

function displayProviderName(provider: ProviderName): string {
  return provider
    .split('-')
    .map((part) => part ? `${part[0]!.toUpperCase()}${part.slice(1)}` : part)
    .join(' ')
}
